# Generated by Django 2.1.5 on 2019-06-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='conteudo',
            field=models.TextField(help_text='Escreva seu comentario', max_length=1000),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(help_text='Escreva sua postagem', max_length=1000),
        ),
    ]
